---
- hosts: all
  become: true
  roles:
    - vim
    - python
    - tmux
  tasks:
  - name: install various
    apt:
      name: "{{item}}"
      update_cache: yes
    with_items:
      - dos2unix
      - libpq-dev
      - postgresql
      - postgresql-contrib
      - nginx
      - rabbitmq-server
