---
- hosts: all
  become: true
  roles:
    - vim
    - python
  tasks:
  - name: install various
    apt:
      name: "{{item}}"
      update_cache: yes
    with_items:
      #- postgresql
      #- postgresql-contrib
      #- sqlite
      - nginx
