---
- hosts: all
  become: true
  roles:
    - python
    - vim
  tasks:
    - name: install firefox xvfb
      apt:
        name: '{{item}}'
      with_items:
        - firefox
        - xvfb 
    - name: create downloads directory
      file:
        path: '/home/ubuntu/{{ item }}'
        state: directory
        owner: ubuntu
        mode: 0755
      with_items:
        - '.local/bin'
