---
- hosts: all
  become: true
  tasks:
  - name: vim config
    file:
      owner: ubuntu
      path: /home/ubuntu/.vimrc
      mode: 0644
      state: touch
  - name: inputrc
    lineinfile:
      owner: ubuntu
      path: /home/ubuntu/.inputrc
      line: 'set editing-mode vi'
      create: yes
  - name: vim directories
    file:
      owner: ubuntu
      path: "/home/ubuntu/.vim/{{item}}"
      state: directory
      mode: 0755
    with_items:
      - bundle
      - autoload
  - name: install git
    apt: name=git state=latest
  - name: install vundle
    git:
      repo: https://github.com/gmarik/Vundle.vim.git
      dest: /home/ubuntu/.vim/bundle/Vundle.vim
  - name: extra vim config
    blockinfile:
      path: /home/ubuntu/.vimrc
      marker: "\" {mark} from playbook"
      block:  "{{ lookup('file', '/vagrant/vimrc') }}"
  - name: install pip virtualenv etc
    apt:
      name='{{item}}' state=latest
    with_items:
      - python-pip
      - python3-pip
      - virtualenv
      - virtualenvwrapper
  - name: virtualenv config for bash-profile
    blockinfile:
      path: /home/ubuntu/.bash-profile
      marker: "\" {mark} from playbook"
      block:  "{{ lookup('file', '/vagrant/bash-profile') }}"
  - name: python testing packages
    pip:
      name: "{{item}}"
      executable: pip3
    with_items:
      - pytest
      - ptvsd
  - name: install sqlite
    apt: name=sqlite3 state=latest
