- name: install python extras
  apt:
    name: '{{item}}'
  with_items:
    - python3-pip
    - virtualenv
- name: install virtualenvwrapper
  pip:
    name: virtualenvwrapper
    executable: pip3
- name: virtualenvwrapper env variable
  lineinfile:
    path: /home/ubuntu/.profile
    line: '{{item}}'
  with_items: 
    - 'export VIRTUALENVWRAPPER_PYTHON=/usr/bin/python3'
    - 'source /usr/local/bin/virtualenvwrapper.sh'
    - 'export PS1="python-vm \W > "'
