- name: vim config directories
  file:
    path: '/home/ubuntu/.vim/{{item}}'
    state: directory
    owner: ubuntu
    mode: 0755
  with_items:
    - 'autoload'
    - 'bundle'
- name: download pathogen
  get_url:
    url: 'https://tpo.pe/pathogen.vim'
    dest: /home/ubuntu/.vim/autoload/pathogen.vim
    owner: ubuntu
    mode: 0644
- name: copy vimrc
  copy:
    # we're running ansible local, so src is path on VM
    src: vimrc
    dest: /home/ubuntu/.vimrc
    owner: ubuntu
    group: ubuntu
    mode: 0644           
    force: no
- name: install nerdtree
  git:
    repo: 'https://github.com/scrooloose/nerdtree.git' 
    dest: /home/ubuntu/.vim/bundle/nerdtree
    update: no
- name: install solarized
  git:
    repo: 'https://github.com/altercation/vim-colors-solarized.git' 
    dest: /home/ubuntu/.vim/bundle/vim-colors-solarized.git 
    update: no
- name: install syntastic
  git:
    repo: 'https://github.com/vim-syntastic/syntastic.git' 
    dest: /home/ubuntu/.vim/bundle/syntastic
    update: no
- name: install powerline
  pip:
    name: powerline-status
    executable: pip3
